### ISSUE TITLE
HDD Discovery works without disks in drives

### ISSUE THREAD

**Issue by epizarro2** [emanueleg/zabbix-templates#1]
Discovery rules get values of empty drives, possible solution with LDD MACROS

root@monitor2:~# snmpwalk -v2c -cpublic -mAll XXX.XXX.XXX.XXX 1.3.6.1.4.1.24681.1.3.11.1.2
SNMPv2-SMI::enterprises.24681.1.3.11.1.2.1 = STRING: "HDD1"
SNMPv2-SMI::enterprises.24681.1.3.11.1.2.2 = STRING: "HDD2"

**Comment by emanueleg** [comment]
Hi! Actually, drive names are not hardcoded and are discovered using the OID you suggest.
https://github.com/emanueleg/zabbix-templates/blob/b5c33ea6197f2081505b3e4d46321fa1aace3c65/QNAP_template_3.x.xml#L1059

In my case HDD1 and HDD2 are internal (eSATA) drives. When no disks is present in slot, the status becomes -5 (No Disk) but the drive is still discovered and listed.

Maybe we could disable all items (temperature, size, etc) if disk is not present (and re-enable them if status changes).
